### PR TITLE
Edited codes

### PR DESCRIPTION
**Pull request by AhmetCefakar**
1) The manual added reference "System.Data.Entity.Design.PluralizationServices.dll" has been removed and added "System.Data.Entity.Design" reference.

2) Edited "TESTS-JSON-to-CSHARP" project codes.

### CODE REVIEW

**Comment by Json2CSharp** [comment]
Hi Ahmet, thanks for making a pull request but what exactly is the problem you are trying to solve

**Comment by AhmetCefakar** [comment]
Hi,
After downloading the repository, the application could not be compiled and run directly.
This change resolves this error.
After this commit, people can download the repository and compile and run the project directly if ".Net Framework 4.6.1" is installed on their system.

**Comment by Json2CSharp** [comment]
oh great, didn't notice that. i'll merge this weekend. Thanks for the help, cheers

**Comment by Json2CSharp** [comment]
I reverted this commit as i had trouble calling the librairy as it was throwing an error that the pluralization dll was missing, ill open an issue with this and check it later

**Comment by Jehoel** [comment]
@Json2CSharp My PR includes a change to remove the hardcoded reference (which I don't have on my machine either) but replaces it with a NuGet reference which reliably works on any modern machine with VS2015 or later (I assume it should work with VS2013 too).

**Pull request merged**
