### PR TITLE
Adding support for generating C# immutable classes, a WinForms GUI, and other misc improvements.

### PR DESCRIPTION
**Pull request by Jehoel**
See https://github.com/Json2CSharp/Json2CSharpCodeGenerator/issues/41

Changes:

- Some code-cleanup. There's loads more I want to do though...
    - Added an `.editorconfig`.
    - Removed hardcoded references to assemblies not included in the repo and replaced them with NuGet package references.
    - Updated incomplete tests to terminate with `Assert.Indeterminate`.
- Added ability to generate immutable C# types using Newtonsoft.Json-compatible constructors.
- Added test-case for immutable types. All relevant tests pass.
- Added a simple WinForms GUI (with support for drag 'n' drop, live updates, high-DPI support, etc).
- Misc changes to C# code-gen:
    - `using: ` namespaces are now sorted with `System.*` namespaces always coming first.
    - Drastically improved codegen performance by using a `HashSet<string>` for `O(1)` keyword checking instead of `O(n)` from the old `List<string>` check.
    - Made indentation logic easier to follow.
    - Addressed many static code-analysis warnings.

------

Screenshot showing normal class generation:

image

Screenshot showing C# immutable class generation:

image

### CODE REVIEW

**Comment by Jehoel** [comment]
@Json2CSharp I'm curious why you removed the `ArgumentException` when the configuration is in an invalid state ( https://github.com/Json2CSharp/Json2CSharpCodeGenerator/commit/3b2a92e8e64560cecc6a43b8a3b05999d9ea771a ) - because you can't use _both_ attributes at the same time, right?

**Comment by Json2CSharp** [comment]
Oh because people just flag both and the code will throw an exception, so by default if you have both flag checked just work with the second flag (.net core attributes), this way the code will still return results

**Comment by Jehoel** [comment]
A better solution would be to have radio inputs in the web-page. Is that possible?

**Comment by Json2CSharp** [comment]
Yes I added an issue, will impelement radio input on the website and uncomment the throw exceptin code

**Pull request merged**
